{{- if and .Values.storegateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true"
{{- end }}
